# Site settings
baseurl = "https://awsug.cz/"
languageCode = "en-us"
title = "Prague AWS User Group"
theme = "hugo-creative-theme"
googleAnalytics = "UA-96620987-2"

[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
    # for more icons. The icons are represented by their corresponding
    # CSS class.

    # All projects of the portfolio are defined in their own files.
    # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
    # folder into the 'data' directory at the root of this Hugo site.
    # For more informtion take a look at the README.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Prague AWS User Group"
    description = "Prague AWS User Group"

    # The path must be relative to the static folder
    favicon = "favicon.ico"


    # Navigation
    [params.navigation]
        brand = "Prague AWS User Group"

        [params.navigation.links]
            about     = "About"
            services  = "Services"
            portfolio = "Meetups"
            contact   = "Contact"


    # Hero section
    [params.hero]
        # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
        slogan     = "Prague AWS User Group"
        subtitle   = "Welcome to [Prague AWS User Group](https://www.meetup.com/Prague-AWS-Meetup/)"
        buttonText = "Find out more ..."


    # About section
    [params.about]
        headline    = "Prague Amazon Web Services User Group"
        description = "We are a community with a mission to educate and connect people interested in [Amazon Web Services](https://aws.amazon.com/) and related technologies."


    # Services section
    [params.services]

        [[params.services.list]]
            icon = "fa-meetup"
            title = "Get social!"
            description = "Join our [Meetup group](https://www.meetup.com/Prague-AWS-Meetup/)"

        [[params.services.list]]
            icon = "fa-podcast"
            title = "We want you to speak!"
            description = "[Submit](https://goo.gl/forms/mFYRDTEL41DCewKP2) your talk proposal"

        [[params.services.list]]
            icon = "fa-github-alt"
            title = "I want to help"
            description = "See our [GitHub](https://github.com/awsugcz) or [presentations](https://github.com/awsugcz/awsug.cz/tree/master/static/presentations)"

        [[params.services.list]]
            icon = "fa-youtube"
            title = "YouTube"
            description = "[YouTube Channel](https://www.youtube.com/playlist?list=PL0Qk7ytdTD262PgKQ1GgFHX2IdYzhWM1E)"

        [[params.services.list]]
            icon = "fa-camera"
            title = "Photos"
            description = "See the Meetup [Photos](https://photos.app.goo.gl/sE5kAt95ipmJ3ypPA)"

        [[params.services.list]]
            icon = "fa-envelope-o"
            title = "Email"
            description = "<awsugcz@gmail.com>"

    # Portfolio modals
        [params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Contact section
    [params.contact]
        headline = "Let's Get In Touch!"
        description = "If you have any questions feel free to send us an email and we will get back to you as soon as possible!"
        email = "awsugcz@gmail.com"
